backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Noticias"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Fecha de Publicación", name: "date", widget: "datetime"}
      - {label: "Categoria", name: "category", widget: "list"}
      - {label: "Encabezado", name: "header", widget: "text"}
      - {label: "Publicación Principal", name: "featuredpost", required: false, widget: "boolean", default: false}
      - {label: "Imagen", name: "featuredimage", required: false, widget: image}
      - {label: "Cuerpo", name: "body", widget: "markdown"}
      - {label: "¿Tiene Video?", name: "isVideo", required: false, widget: "boolean", default: false}
      - {label: "Video", name: "video", required: false, widget: "markdown"}